package com.cyberknights4911.robot.commands;

import com.cyberknights4911.robot.subsystems.ClawSubsystem;

import edu.wpi.first.wpilibj2.command.CommandBase;


public class DefaultCollectorCommand extends CommandBase {

    private ClawSubsystem mClaw;

    public void CloseClaw(ClawSubsystem subsystem) {


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
            // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
            // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

            mClaw = subsystem;
            addRequirements(mClaw);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        }

        public void initialize() {
            mClaw.back(); // (1)
        }

        // Called every time the scheduler runs while the command is scheduled.
        @Override
        public void execute() {
        }

        // Called once the command ends or is interrupted.
        @Override
        public void end(boolean interrupted) {
            mClaw.stop(); // (3)
        }




        @Override
        public boolean runsWhenDisabled() {
            // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
            return false;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        }
}
